### ISSUE TITLE
Add FeatureExtractor/TaskTransformer aggregations for Sampler

### ISSUE THREAD

**Issue by beasteers** [bmcfee/pumpp#116]
Task Transformers/FeatureExtractors should be able to specify a mode of aggregation that the sampler can use over any temporal slices taken. An example use case would be if you had a task transformer with time varying labels and you want to take the first, or center one, or the mode, etc. over each window.

```python

# Changes proposed 

class Sampler(Slicer):
    def sample(self, data, interval, aggs=None):
        ...

        for key in data:
            ...
            data_slice[key] = data[key][tuple(index)]

            if aggs and aggs.get(key):
                data_slice[key] = aggs[key](data_slice, axis=self._time[key])

class Pump:
    def __init__(self, *a, **kw):
        ...
        self.aggs = {}

    def add(self, operator):
        ...
        self.aggs.update(operator.aggs)

class Scope:
    def __init__(self, ...):
        ...
        self.aggs = {}
        
    def register(self, field, shape, dtype, agg=None):
        ...
        if agg:
            self.aggs[self.scope(field)] = agg

# An example

class Task(BaseTaskTransformer):

    def __init__(*a, hop_length=512, **kw):
        super().__init__(*a, **kw)
        # agg = np.mean
        # agg = sp.stats.mode
        agg = lambda x: axis=None: x[0]
        self.register('i', (1,), np.int, agg=agg)

    def transform_audio(self, ann, duration):
        return {'i': np.arange(0, duration, self.hop_length)}

pump = Pumpp(..., Task(...))
sampler = pump.sampler(...)

file = librosa.util.example_audio_file()
sampler.sample(pump.transform(file), aggs=pump.aggs)

```

Seeing as the sampler doesn't have a reference to `pump`, we would need to pass the aggregations in addition to the data to `sampler.sample`.

**Comment by bmcfee** [comment]
This seems pretty specific IMO.  I know it's slightly less efficient to do this way, but why not just handle this as a post-processing step between pumpp and whatever consumes your data?

**Comment by beasteers** [comment]
Yeah that's an option. I was just trying to maintain a separation of concerns so that downstream handling wouldn't be pump specific. I can find a work around that doesn't involve touching the pumpp internals tho. I was just wondering if this was something that other ppl deal with

**Comment by beasteers** [comment]
Yeah that works too. It's more about keeping a separation of concerns and having any aggregations be coupled to the pump instead of being handled in two different places. I might have a thought on how to do something like this without touching pumpp internally so no worries
