### ISSUE TITLE
Relying on "keras only" for building layers is limiting!

### ISSUE THREAD

**Issue by cloudscapes** [bmcfee/pumpp#130]

**Comment by cloudscapes** [comment]
Hi there,
in the base.py the api == keras and based on this in the feature folder the base.py :
`if api == 'keras':
            return self.layers_keras()
        else:
            raise ParameterError('Unsupported layer api={}'.format(api))`

why only relying on keras? pumpp could allow the user itself to choose its backend. 

This : 
`def layers_keras(self):
        from .keras.layers import Input
`
could also be : 
`def layers_keras(self):
        from tensorflow.keras.layers import Input`

and now the user can rely on TensorFlow or one could allow for either Keras or tensorflow.keras as 
a backend.

Cheers, 
H

**Comment by bmcfee** [comment]
This is redundant with #109

**Comment by bmcfee** [comment]
Fixed by merging #134
